name: AutoCoder Workflow
on:
  issues:
    types: [opened, reopened, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  access_issue_info:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Make Script Executable
        run: chmod +x scripts/script.sh

      - name: Run Script
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OUTPUT_DIR: autocoder-artifact
        run: |
          ./scripts/script.sh

      - name: Commit Changes
        run: |
          git config --local user.name "autocoder-bot"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Add code snippets for issue #${{ github.event.issue.number }}" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          branch: autocoder-branch-${{ github.event.issue.number }}
          base: main
          labels: autocoder-bot
          title: "Add code snippets for issue #${{ github.event.issue.number }}"
