name: AutoCoder Workflow
on:
  issues:
    types: [opened, reopened, labeled]

jobs:
  access_issue_info:
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Make Script Executable
        run: chmod +x scripts/script.sh

      - name: Run Script
        env:
          GITHUB_TOKEN: ${{ github.token }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OUTPUT_DIR: autocoder-artifact
        run: |
          ./scripts/script.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact
          if-no-files-found: error

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact

      - name: List Files Recursively
        run: ls -R autocoder-artifact
